CREATE TABLE usuarios (
    id VARCHAR(50) PRIMARY KEY,
    nome VARCHAR(100) NOT NULL
);

CREATE TABLE produtos (
    id VARCHAR(50) PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    grupo VARCHAR(30) NOT NULL,
    CONSTRAINT ck_produtos_grupo
        CHECK (grupo IN ('PELUCIAS', 'CARRINHO_PIPOCA'))
);

CREATE TABLE estoques (
    id VARCHAR(50) PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    responsavel_id VARCHAR(50),
    CONSTRAINT fk_estoques_responsavel
        FOREIGN KEY (responsavel_id) REFERENCES usuarios (id),
    CONSTRAINT uq_estoques_responsavel
        UNIQUE (responsavel_id)
);

CREATE TABLE estoque_itens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    estoque_id VARCHAR(50) NOT NULL,
    produto_id VARCHAR(50) NOT NULL,
    quantidade INTEGER NOT NULL,
    CONSTRAINT fk_estoque_itens_estoque
        FOREIGN KEY (estoque_id) REFERENCES estoques (id),
    CONSTRAINT fk_estoque_itens_produto
        FOREIGN KEY (produto_id) REFERENCES produtos (id),
    CONSTRAINT ck_estoque_itens_quantidade_nao_negativa
        CHECK (quantidade >= 0),
    CONSTRAINT uq_estoque_itens_estoque_produto
        UNIQUE (estoque_id, produto_id)
);

CREATE INDEX idx_estoque_itens_produto
    ON estoque_itens (produto_id);
