CREATE TABLE retiradas (
    id UUID PRIMARY KEY,
    responsavel_id VARCHAR(50) NOT NULL,
    estoque_origem_id VARCHAR(50) NOT NULL,
    estoque_destino_id VARCHAR(50) NOT NULL,
    data TIMESTAMP WITH TIME ZONE NOT NULL,
    observacao VARCHAR(500),
    CONSTRAINT fk_retiradas_responsavel
        FOREIGN KEY (responsavel_id) REFERENCES usuarios (id),
    CONSTRAINT fk_retiradas_origem
        FOREIGN KEY (estoque_origem_id) REFERENCES estoques (id),
    CONSTRAINT fk_retiradas_destino
        FOREIGN KEY (estoque_destino_id) REFERENCES estoques (id)
);

CREATE TABLE retirada_itens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    retirada_id UUID NOT NULL,
    produto_id VARCHAR(50) NOT NULL,
    quantidade INTEGER NOT NULL,
    saldo_anterior INTEGER NOT NULL,
    saldo_posterior INTEGER NOT NULL,
    CONSTRAINT fk_retirada_itens_retirada
        FOREIGN KEY (retirada_id) REFERENCES retiradas (id),
    CONSTRAINT fk_retirada_itens_produto
        FOREIGN KEY (produto_id) REFERENCES produtos (id),
    CONSTRAINT ck_retirada_itens_quantidade_positiva
        CHECK (quantidade > 0),
    CONSTRAINT ck_retirada_itens_saldos_nao_negativos
        CHECK (saldo_anterior >= 0 AND saldo_posterior >= 0),
    CONSTRAINT uq_retirada_itens_retirada_produto
        UNIQUE (retirada_id, produto_id)
);

CREATE INDEX idx_retiradas_responsavel_data
    ON retiradas (responsavel_id, data DESC);
