ALTER TABLE reserva_eventos
    DROP CONSTRAINT ck_reserva_eventos_tipo;

ALTER TABLE reserva_eventos
    ADD CONSTRAINT ck_reserva_eventos_tipo CHECK (
        tipo IN ('CRIACAO', 'CANCELAMENTO', 'UTILIZACAO', 'CONCLUSAO')
    );

CREATE TABLE abastecimentos (
    id UUID PRIMARY KEY,
    responsavel_id VARCHAR(50) NOT NULL REFERENCES usuarios(id),
    estoque_origem_id VARCHAR(50) NOT NULL REFERENCES estoques(id),
    local_id VARCHAR(50) NOT NULL,
    data TIMESTAMP WITH TIME ZONE NOT NULL,
    observacao VARCHAR(500),
    CONSTRAINT ck_abastecimentos_local CHECK (
        local_id IN (
            'BOULEVARD',
            'AEROPORTO',
            'MERCADOS',
            'SUPERMAGO_BOA_VISTA'
        )
    )
);

CREATE TABLE abastecimento_itens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    abastecimento_id UUID NOT NULL REFERENCES abastecimentos(id),
    maquina_id VARCHAR(100) NOT NULL,
    produto_id VARCHAR(50) NOT NULL REFERENCES produtos(id),
    quantidade INTEGER NOT NULL,
    CONSTRAINT ck_abastecimento_itens_quantidade CHECK (quantidade > 0)
);

CREATE INDEX idx_abastecimentos_responsavel_data
    ON abastecimentos (responsavel_id, data DESC);

CREATE TABLE abastecimento_saldos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    abastecimento_id UUID NOT NULL REFERENCES abastecimentos(id),
    produto_id VARCHAR(50) NOT NULL REFERENCES produtos(id),
    quantidade INTEGER NOT NULL,
    saldo_anterior INTEGER NOT NULL,
    saldo_posterior INTEGER NOT NULL,
    CONSTRAINT ck_abastecimento_saldos_quantidade CHECK (quantidade > 0),
    CONSTRAINT ck_abastecimento_saldos_nao_negativos CHECK (
        saldo_anterior >= 0 AND saldo_posterior >= 0
    ),
    CONSTRAINT uq_abastecimento_saldos_produto UNIQUE (
        abastecimento_id,
        produto_id
    )
);
