ALTER TABLE reserva_eventos
    DROP CONSTRAINT ck_reserva_eventos_tipo;

ALTER TABLE reserva_eventos
    ADD CONSTRAINT ck_reserva_eventos_tipo CHECK (
        tipo IN (
            'CRIACAO',
            'CANCELAMENTO',
            'UTILIZACAO',
            'LIBERACAO',
            'CONCLUSAO'
        )
    );

CREATE TABLE devolucoes (
    id UUID PRIMARY KEY,
    responsavel_id VARCHAR(50) NOT NULL REFERENCES usuarios(id),
    estoque_origem_id VARCHAR(50) NOT NULL REFERENCES estoques(id),
    estoque_destino_id VARCHAR(50) NOT NULL REFERENCES estoques(id),
    data TIMESTAMP WITH TIME ZONE NOT NULL,
    observacao VARCHAR(500)
);

CREATE TABLE devolucao_itens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    devolucao_id UUID NOT NULL REFERENCES devolucoes(id),
    produto_id VARCHAR(50) NOT NULL REFERENCES produtos(id),
    quantidade_livre INTEGER NOT NULL,
    quantidade_reservada INTEGER NOT NULL,
    quantidade_total INTEGER NOT NULL,
    saldo_pessoal_anterior INTEGER NOT NULL,
    saldo_pessoal_posterior INTEGER NOT NULL,
    saldo_principal_anterior INTEGER NOT NULL,
    saldo_principal_posterior INTEGER NOT NULL,
    CONSTRAINT ck_devolucao_itens_quantidades CHECK (
        quantidade_livre >= 0
        AND quantidade_reservada >= 0
        AND quantidade_total > 0
        AND quantidade_total = quantidade_livre + quantidade_reservada
    ),
    CONSTRAINT ck_devolucao_itens_saldos CHECK (
        saldo_pessoal_anterior >= 0
        AND saldo_pessoal_posterior >= 0
        AND saldo_principal_anterior >= 0
        AND saldo_principal_posterior >= 0
    ),
    CONSTRAINT uq_devolucao_itens_produto UNIQUE (devolucao_id, produto_id)
);

CREATE TABLE devolucao_reservas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    devolucao_item_id BIGINT NOT NULL REFERENCES devolucao_itens(id),
    reserva_id UUID NOT NULL REFERENCES reservas(id),
    destino_id VARCHAR(50) NOT NULL,
    quantidade INTEGER NOT NULL,
    CONSTRAINT ck_devolucao_reservas_quantidade CHECK (quantidade > 0)
);

CREATE INDEX idx_devolucoes_responsavel_data
    ON devolucoes (responsavel_id, data DESC);
