CREATE TABLE movimentos_estoque_principal (
    id UUID PRIMARY KEY,
    tipo VARCHAR(20) NOT NULL,
    data TIMESTAMP WITH TIME ZONE NOT NULL,
    observacao VARCHAR(500),
    CONSTRAINT ck_movimentos_principal_tipo CHECK (
        tipo IN ('ENTRADA', 'SAIDA')
    )
);

CREATE TABLE movimento_estoque_principal_itens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    movimento_id UUID NOT NULL REFERENCES movimentos_estoque_principal(id),
    produto_id VARCHAR(50) NOT NULL REFERENCES produtos(id),
    quantidade INTEGER NOT NULL,
    saldo_anterior INTEGER NOT NULL,
    saldo_posterior INTEGER NOT NULL,
    CONSTRAINT ck_movimento_principal_itens_quantidade CHECK (quantidade > 0),
    CONSTRAINT ck_movimento_principal_itens_saldos CHECK (
        saldo_anterior >= 0 AND saldo_posterior >= 0
    ),
    CONSTRAINT uq_movimento_principal_produto UNIQUE (
        movimento_id,
        produto_id
    )
);

CREATE INDEX idx_movimentos_principal_data
    ON movimentos_estoque_principal (data DESC);
