CREATE TABLE consumos_carrinho (
    id UUID PRIMARY KEY,
    responsavel_id VARCHAR(50) NOT NULL REFERENCES usuarios(id),
    estoque_origem_id VARCHAR(50) NOT NULL REFERENCES estoques(id),
    data TIMESTAMP WITH TIME ZONE NOT NULL,
    observacao VARCHAR(500)
);

CREATE TABLE consumo_carrinho_itens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    consumo_id UUID NOT NULL REFERENCES consumos_carrinho(id),
    produto_id VARCHAR(50) NOT NULL REFERENCES produtos(id),
    quantidade INTEGER NOT NULL,
    saldo_anterior INTEGER NOT NULL,
    saldo_posterior INTEGER NOT NULL,
    CONSTRAINT ck_consumo_carrinho_itens_quantidade CHECK (quantidade > 0),
    CONSTRAINT ck_consumo_carrinho_itens_saldos CHECK (
        saldo_anterior >= 0 AND saldo_posterior >= 0
    ),
    CONSTRAINT uq_consumo_carrinho_produto UNIQUE (consumo_id, produto_id)
);

CREATE INDEX idx_consumos_carrinho_responsavel_data
    ON consumos_carrinho (responsavel_id, data DESC);
