spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/stockflow}
    username: ${DB_USERNAME:stockflow}
    password: ${DB_PASSWORD:stockflow}
  jpa:
    properties:
      hibernate:
        format_sql: true

stockflow:
  auth:
    jwt-secret: ${AUTH_JWT_SECRET:segredo-local-desenvolvimento-stockflow-32-bytes}
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:8081,http://127.0.0.1:8081}
